# Deny access to sudo after that many failures
deny = 5

# Count only recent failures within this window (seconds)
fail_interval = 900

# Deny access for (in seconds)
unlock_time = 300

# Protect privileged accounts as well
even_deny_root

# Root lockout duration (in seconds)
root_unlock_time = 600